project:
  type: website

website:
  title: "sql4science"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: about.qmd
        text: About
      - href: what_is_db_sw.qmd
        text: What is Database?

format:
  html:
    theme: spaceman
    css: styles.css
    toc: true

editor: visual

