project:
  type: book

book:
  title: "sql4science"
  author: "Patrick Bills"
  date: "9/24/2023"
  chapters:
    - index.qmd
    - about.qmd
    - what_is_db_sw.qmd
    - quick_sqldf_demo.qmd
    - db_services.qmd

format:
  html:
    theme: spaceman
    css: styles.css
    toc: true

editor: visual

