project:
  type: book

book:
  title: "What they Forgot to teach about SQL"
  author: "Patrick Bills"
  date: "9/24/2023"
  chapters:
    - index.qmd
    - about.qmd
    - what_is_db_sw.qmd
    - quick_sqldf_demo.qmd
    - db_engines.qmd
    - db_services.qmd
    - research_db_case_studies.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

