---
title: "Introduction"
editor: 
  mode: source
---

# Motivation: SQL is everywhere, except in data science.

Researchers in all disciplines have to manage tremendous amounts of data, but many have large collection of files of various formats such as CSV text files, spreadsheets, lists, even images, maps, movies, etc.

We've heard of database and of the SQL language that works with databases and want to learn more.

SQL is the common language used to interact with "Relational" databases. Relational database excel at organizing tabular data and reading data from it at unbelievable speed.

The goal of this book is to provide all the background information someone doing research in any field (sciences or humanities). Not all academic work is 'research' but nonetheless could use a system to quickly query a large colleciton of information to find or summarize. A library card catalog for example is an extremely helpful database. Faculty, staff and students don't have time or resources to purchase commercial database systems. There are many many introductions to the SQL language which focus on pulling data from it. Few provide the complete picture of exactly what you need to complete your research. How do you create the database to hold your information, and how to get your information into the database. Some of focused on a specific brand of database but that may not be the best fit for what you need to accomplish.

SQL has been around for a long time, and databases are everywhere. There is one in your phone. There are many many good tutorials on the SQL language, and the SQL language is not hard to learn. If that's true, then why don't we see more adoption of SQL in academia or for research data? I believe it's not the fault of SQL but because the following are not clearly explained if even discussed:

-   how to model data using the linked tables (the relational model)
-   understanding what a data server is and how to maintain one for your work group for collaboration
-   if the data is not from an instrument or must be edited manually (as some portion of most of our data is), how to get the data in to the database or even harder, a standard data entry process. Some of the questions academic left to answer are:

Data entry seems to be the topic no one wants to talk about in data science. Database seem like a fantastic tool for quering your data, but how do you get your data into a database in the first place? Researchers frequently need to carefully curate data they collect, even if it's from a machine.

How can I enter data as I am collecting it into a database.

How can I use a database only on my laptop without having to purcahse any other hardware? That is, do I need a server? How much will everything cost? What are some really low cost ways to to share my data with my collaborators with with the world?

How can I share the database with my collaborators?

Can multiple people use the database at the same time, or could have some helpers entering data while others are reading data?

What are some guidelines for building a database structure for my data?
